[package]
name = "uf-ahrs"
version = "0.1.0"
edition = "2024"

[dependencies]
idsp = "0.19.0"
libm = "0.2.15"
nalgebra = { version = "0.34.1", default-features = false, features = ["libm"] }

[dev-dependencies]
approx = "0.5.1"
